### ISSUE TITLE
Ringpop: should support forwarding tchannel requests

### ISSUE THREAD

**Issue by Raynos** [uber/ringpop-node#138]
Ringpop currently supports forwarding HTTP requests. We should add tchannel support.

Doing so should be pretty trivial as tchannel v2 comes with a relay handler.

**Comment by sashahilton00** [comment]
Any update on this @Raynos? would be nice to be doing everything in TChannel where possible, and I thought I saw a mention on upgrading TChannel in one of the previous issues... Ty

**Comment by Raynos** [comment]
@sashahilton00 

We have ringpop-handler ( https://github.com/uber/ringpop-node/blob/master/ringpop-handler.js#L25 ) now.

See the example ( https://github.com/uber/ringpop-node/blob/master/examples/tchannel-forwarding.js ).

So it's done :)
